### ISSUE TITLE
Add curves to Wavefront (.obj)

### ISSUE THREAD

**Issue by FabioMoreiraFM** [ramnasidharta/graphical-recipe#39]

**Comment by ramnaq** [comment]
Is that really necessary? I'm not sure, because our GIS is already showing objects like sub-zero, with about 11000 vertices, without in fact reading curves (take a look in the above image). Also, I talked with some people which told me they finished the program, but didn't implemented it.

Besides that, I'm confused about how that would be in terms of our program design. An `Object3D` is instantiated with a vector of type `Segment`, which in turn, has just two objects of type `Coordinate`. How a curve would fit in our design?

![photo_2019-05-29_21-36-49](https://user-images.githubusercontent.com/29432227/58600175-e78d2d00-8259-11e9-9f86-212223b17d6c.jpg)

**Comment by FabioMoreiraFM** [comment]
I understand that we need to support both object 2D (Point, Line, Polygon and Curve) and 3D (Object3D and Bicubic surfaces).

For instance, if we create a new curve, is it possible to save and load the generated object in wavefront format?

**Comment by ramnaq** [comment]
I see your point and I agree with you. It is not possible to do that! I'll think about how I will redesign the logic for support it, because 3D objects are instantiated with Segments, which are pairs of points, and polygons (2D) also use a sequence of points.

I'll commit some changes tonight. Thank you!
